### ISSUE TITLE
Version 2 Checklist

### ISSUE THREAD

**Issue by austinbuckler** [austinbuckler/bubblr#5]
Todo for version 2.0
- [ ] Use MEAN Stack (or variation of: EmberJS, or ReactJS).
- [ ] Implement Elasticsearch.
- [ ] Implement caching.
- [ ] Save new queries to a database.
- [ ] Append new data to old already stored data.
- [ ] Slick new look.
